-- 임진강김치 MES 수집 관련 테이블 (SF-TD5 원문 컬럼명). SQLite로 옮기며 BIGSERIAL → INTEGER PK,
-- TIMESTAMP → ISO8601 TEXT, JSONB → TEXT. '-- 트윈' 표시 컬럼은 트윈 전용 보조 컬럼 (docs/ARCHITECTURE.md 4장)

CREATE TABLE IF NOT EXISTS BAS_EQUIP (
  EQUIP_ID INTEGER PRIMARY KEY,
  EQUIP_CODE VARCHAR(30) NOT NULL UNIQUE,      -- PLC 태그와 1:1 매핑
  EQUIP_NAME VARCHAR(100) NOT NULL,
  EQUIP_TYPE VARCHAR(30) NOT NULL,
  PROCESS_ID BIGINT,
  PROCESS_NAME VARCHAR(50),                    -- 트윈: BAS_PROCESS 대신 공정명
  PLC_TAG VARCHAR(100),
  COMM_TYPE VARCHAR(30),
  COLLECT_ITEM VARCHAR(300),
  USE_YN CHAR(1) NOT NULL DEFAULT 'Y',
  CREATED_DT TIMESTAMP NOT NULL,
  UPDATED_DT TIMESTAMP
);

CREATE TABLE IF NOT EXISTS BAS_CCP_STD (
  CCP_STD_ID INTEGER PRIMARY KEY,
  CCP_CODE VARCHAR(30) NOT NULL UNIQUE,        -- 트윈: ccp_std.yaml id
  CCP_ITEM VARCHAR(50) NOT NULL,
  EQUIP_CODES VARCHAR(200) NOT NULL,
  LOW_LIMIT NUMERIC(10,3),
  HIGH_LIMIT NUMERIC(10,3),
  BAND NUMERIC(10,3),
  UNIT_CD VARCHAR(20),
  HOLD_SEC NUMERIC(10,1) NOT NULL DEFAULT 0,
  SEVERITY VARCHAR(10) NOT NULL,
  BASIS VARCHAR(20) NOT NULL,                  -- 설계 / 가정
  CREATED_DT TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS ORD_WORK_ORDER (
  WORK_ORDER_ID INTEGER PRIMARY KEY,
  WORK_ORDER_NO VARCHAR(30) NOT NULL,
  LOT_NO VARCHAR(50),
  ITEM_ID BIGINT,
  CREATED_DT TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS IF_SENSOR_RAW (
  RAW_ID INTEGER PRIMARY KEY,
  EQUIP_ID BIGINT NOT NULL REFERENCES BAS_EQUIP(EQUIP_ID),
  TAG_ADDR VARCHAR(100) NOT NULL,
  DATA_TYPE VARCHAR(30) NOT NULL,
  RAW_VALUE VARCHAR(100) NOT NULL,
  UNIT_CD VARCHAR(20),
  COMM_TYPE VARCHAR(20) NOT NULL,
  TARGET_TABLE VARCHAR(50),
  RESEND_YN CHAR(1) NOT NULL,
  COLLECT_DT TIMESTAMP NOT NULL,
  MSG_ID VARCHAR(40) NOT NULL UNIQUE,          -- 트윈: 중복 적재 방지
  ITEM_KEY VARCHAR(30) NOT NULL,               -- 트윈: 항목 키
  RECEIVED_DT TIMESTAMP NOT NULL               -- 트윈: MES 수신 시각
);
CREATE INDEX IF NOT EXISTS IX_RAW_EQUIP ON IF_SENSOR_RAW(EQUIP_ID, RAW_ID);
CREATE INDEX IF NOT EXISTS IX_RAW_RESEND ON IF_SENSOR_RAW(RESEND_YN);

CREATE TABLE IF NOT EXISTS SLT_TANK_OPR (
  TANK_OPR_ID INTEGER PRIMARY KEY,
  EQUIP_ID BIGINT,
  TANK_NO INTEGER NOT NULL,                    -- 트윈: 절임통 번호 1~8
  TARGET_SALINITY NUMERIC(5,2) NOT NULL,       -- 트윈: 절임 조건 염도
  PLAN_HOURS NUMERIC(6,2) NOT NULL,            -- 트윈: 24/48 h
  START_DT TIMESTAMP NOT NULL,
  END_DT TIMESTAMP,
  TANK_STATUS VARCHAR(20) NOT NULL             -- 절임중 / 완료
);

CREATE TABLE IF NOT EXISTS SLT_SALINITY_LOG (
  SALINITY_LOG_ID INTEGER PRIMARY KEY,
  TANK_OPR_ID BIGINT NOT NULL REFERENCES SLT_TANK_OPR(TANK_OPR_ID),
  SENSOR_ID VARCHAR(30),
  SALINITY_VALUE NUMERIC(5,2) NOT NULL,
  ELAPSED_HOURS NUMERIC(6,2),
  ALARM_YN CHAR(1) NOT NULL,
  COLLECT_TYPE VARCHAR(20) NOT NULL,
  MEASURE_DT TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS WSH_SANITIZER_LOG (
  SANITIZER_LOG_ID INTEGER PRIMARY KEY,
  EQUIP_ID BIGINT NOT NULL,
  WORK_ORDER_ID BIGINT,
  PPM_VALUE NUMERIC(6,2) NOT NULL,
  CONTACT_TIME NUMERIC(8,2),
  DOSING_RATE NUMERIC(6,2),
  ALARM_YN CHAR(1) NOT NULL,
  COLLECT_DT TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS AGE_ENV_LOG (
  ENV_LOG_ID INTEGER PRIMARY KEY,
  EQUIP_ID BIGINT NOT NULL,
  SENSOR_ID VARCHAR(30),
  TEMP_VALUE NUMERIC(6,2),
  HUMID_VALUE NUMERIC(6,2),
  SET_TEMP NUMERIC(6,2),
  COMM_TYPE VARCHAR(20) NOT NULL,
  COLLECT_DT TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS AGE_ENV_ALARM (
  ENV_ALARM_ID INTEGER PRIMARY KEY,
  ENV_LOG_ID BIGINT NOT NULL REFERENCES AGE_ENV_LOG(ENV_LOG_ID),
  CCP_STD_ID BIGINT,
  ALARM_ITEM VARCHAR(30) NOT NULL,
  ALARM_VALUE NUMERIC(6,2) NOT NULL,
  CONFIRM_YN CHAR(1) NOT NULL DEFAULT 'N',
  ACTION_DESC VARCHAR(500),
  ALARM_DT TIMESTAMP NOT NULL,
  CREATED_DT TIMESTAMP NOT NULL,
  UPDATED_DT TIMESTAMP
);

CREATE TABLE IF NOT EXISTS QUA_METAL_LOG (
  METAL_LOG_ID INTEGER PRIMARY KEY,
  EQUIP_ID BIGINT NOT NULL,
  WORK_ORDER_ID BIGINT NOT NULL,
  LOT_NO VARCHAR(50) NOT NULL,
  DETECT_RESULT VARCHAR(10) NOT NULL,
  INSPECT_QTY NUMERIC(12,3),
  NG_QTY NUMERIC(12,3),
  ALARM_YN CHAR(1) NOT NULL,
  COLLECT_DT TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS PKG_TAPING_LOG (
  TAPING_LOG_ID INTEGER PRIMARY KEY,
  EQUIP_ID BIGINT NOT NULL,
  WORK_ORDER_ID BIGINT NOT NULL,
  PACK_QTY NUMERIC(12,3) NOT NULL,
  RUN_STATUS VARCHAR(20),
  RUN_MINUTES NUMERIC(10,2),
  COLLECT_TYPE VARCHAR(20) NOT NULL,
  COLLECT_DT TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS PKG_WEIGHT_INSP (
  WEIGHT_INSP_ID INTEGER PRIMARY KEY,
  WORK_ORDER_ID BIGINT NOT NULL,
  ITEM_ID BIGINT NOT NULL,
  STD_WEIGHT NUMERIC(10,3) NOT NULL,
  MEASURE_WEIGHT NUMERIC(10,3) NOT NULL,
  GAP_WEIGHT NUMERIC(10,3),
  JUDGE_RESULT VARCHAR(20) NOT NULL,           -- 합격 / 미달 / 초과
  DEFECT_ID BIGINT,
  INSPECT_DT TIMESTAMP NOT NULL,
  CREATED_DT TIMESTAMP NOT NULL,
  UPDATED_DT TIMESTAMP
);

CREATE TABLE IF NOT EXISTS MIX_FILLER_LOG (
  FILLER_LOG_ID INTEGER PRIMARY KEY,
  EQUIP_ID BIGINT NOT NULL,
  WORK_ORDER_ID BIGINT NOT NULL,
  BATCH_NO VARCHAR(30) NOT NULL,
  WORK_SPEED NUMERIC(10,2),
  SET_VOLUME NUMERIC(10,2),
  SETTING_JSON TEXT,
  COLLECT_TYPE VARCHAR(20) NOT NULL,
  COLLECT_DT TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS EQP_RUN_LOG (
  RUN_LOG_ID INTEGER PRIMARY KEY,
  EQUIP_ID BIGINT NOT NULL,
  RUN_STATUS VARCHAR(20) NOT NULL,             -- 가동 / 비가동
  STOP_CODE VARCHAR(30),
  START_DT TIMESTAMP NOT NULL,
  END_DT TIMESTAMP,
  STOP_MINUTES NUMERIC(10,2),
  INPUT_TYPE VARCHAR(20) NOT NULL,
  USER_ID BIGINT,
  CREATED_DT TIMESTAMP NOT NULL,
  UPDATED_DT TIMESTAMP
);

-- 트윈 전용 통합 알람 (D-006)
CREATE TABLE IF NOT EXISTS TWIN_ALARM (
  ALARM_ID INTEGER PRIMARY KEY,
  CATEGORY VARCHAR(10) NOT NULL,               -- CCP / COMM
  RULE_ID VARCHAR(30) NOT NULL,
  ITEM VARCHAR(50) NOT NULL,
  EQUIP_CODE VARCHAR(30) NOT NULL,
  SEVERITY VARCHAR(10) NOT NULL,
  MESSAGE VARCHAR(300) NOT NULL,
  VALUE VARCHAR(50),
  VALUE_KEY VARCHAR(30),                       -- 조건 구분(절임통 번호, 통신 대상)
  STATE VARCHAR(10) NOT NULL,                  -- RAISED / ACKED / CLEARED
  RAISED_DT TIMESTAMP NOT NULL,
  ACKED_DT TIMESTAMP,
  CLEARED_DT TIMESTAMP
);
CREATE INDEX IF NOT EXISTS IX_ALARM_STATE ON TWIN_ALARM(STATE);

-- 트윈 전용 일일 정리 이력 (D-017)
CREATE TABLE IF NOT EXISTS TWIN_PURGE_LOG (
  PURGE_ID INTEGER PRIMARY KEY,
  TRIGGER_TYPE VARCHAR(10) NOT NULL,           -- SCHEDULE / MANUAL
  STARTED_DT TIMESTAMP NOT NULL,
  CUTOFF_DT TIMESTAMP NOT NULL,                -- 이 시각 이전 수집분 삭제
  DELETED_JSON TEXT NOT NULL,                  -- 테이블별 삭제 행 수
  DELETED_TOTAL INTEGER NOT NULL,
  DB_BYTES_BEFORE INTEGER,
  DB_BYTES_AFTER INTEGER,
  ELAPSED_MS INTEGER NOT NULL
);
